---
- name: test playbook
  hosts: '{{ edge }}'
  connection: netconf
  gather_facts: false
  roles:
  - Juniper.junos
  tasks:
  - name: Show interfaces
    junos_command:
      commands: show interfaces terse
    register: variable
  - name: Print state of interfaces
    debug:
      var: variable
    tags: interfaces
 
  - name: Show routing table
    junos_command:
      commands: show route
    register: variable1
  - name: Print routing table
    debug:
      var: variable1
    tags: route  
