---
- name: test playbook
  hosts: '{{ edge }}'
  connection: netconf
  gather_facts: false
  roles:
  - Juniper.junos
  tasks:
  - name: SHOW INTERFACES TERSE
    junos_command:
      commands: show interfaces terse
    register: interfaces
#  - name: Print state of interfaces
  - debug: var=interfaces
    tags: interfaces
 
  - name: SHOW ROUTE
    junos_command:
      commands: show route
    register: route
  - name: Print output
  - debug: var=route
    tags: route
    

#    tags: print
