---
- name: test playbook
  hosts: all
  connection: netconf
  
  - name: Push command
    junos_command:
      commands: show version
    register: variable
  - name: Print
    debug:
      var: variable
