---
- name: test playbook
  hosts: all
  connection: netconf
  gather_facts: no
  tasks:
  - name: Estrazione facts
    junos_facts:
      timeout: 1000
      config_format: json
      gather_subset:
