---
- name: test playbook
  hosts: '{{ edge }}'
  connection: netconf
  gather_facts: false
  roles:
  - Juniper.junos
  tasks:
  - name: Test role
    junos_command:
      commands: show interfaces terse
    register: variable
  - name: Print version
    debug:
      var: variable.stdout_lines
